### ISSUE TITLE
Azure NextGen ServiceBus preview since 2018?

### ISSUE THREAD

**Issue by fabiomilheiro** [pulumi/pulumi-azure-nextgen#193]
I was just about to convert a service bus namespace from `Pulumi.Azure` to `Pulumi.AzureNextGen` and see this:

![image](https://user-images.githubusercontent.com/442911/103359700-3e9b5980-4ab0-11eb-9f6a-61e96bba8280.png)

2018 preview? That makes me a bit unsettled. Should I hold on and stop converting to `AzureNextGen`?

**Comment by mikhailshilkov** [comment]
We expose exactly the same versions as Azure Open API specs: https://github.com/Azure/azure-rest-api-specs/tree/master/specification/servicebus/resource-manager/Microsoft.ServiceBus

The old provider is based on the Terraform provider which uses `2018-01-01-preview`: https://github.com/terraform-providers/terraform-provider-azurerm/blob/fdc385bf7351656589770fefbd87eb422f53f2a1/azurerm/internal/services/servicebus/servicebus_namespace_resource.go#L9

Having said that, if you want to use a stable version - go for `V20170401`, that's why we give you a choice. The `Latest` version also points to the same stable version.

**Comment by fabiomilheiro** [comment]
All right, I was assuming it could be Pulumi possibly taking to long to make it stable but I understand now it relies on Azure. Thanks for explaining 👍
