### ISSUE TITLE
Difference between DatabaseAccountSqlDatabase and SqlResourceSqlDatabase

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure-nextgen#26]
The `documentdb.latest` module contains two resources that seem to do the same operation: `DatabaseAccountSqlDatabase` and `SqlResourceSqlDatabase`. Why are they both there and what is the difference?

**Comment by mikhailshilkov** [comment]
The `latest` version is produced by searching for unique resource paths in all stable API versions and finding the last version of each path. That path then defines the resource name. We do that because many resource providers don't publish all resources in each version but only a subset of resources that changed.

For Document DB, there are two paths to create a SQL Database:

- `2020-04-01` has the path [/Microsoft.DocumentDB/databaseAccounts/{accountName}/sqlDatabases/{databaseName}](https://github.com/Azure/azure-rest-api-specs/blob/7d9eaf4c9866664806a2202b02e3ab5259c86cf9/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2020-04-01/cosmos-db.json#L1482) with the operation ID `SqlResources_GetSqlDatabase`
- `2016-03-01` has the path [/Microsoft.DocumentDB/databaseAccounts/{accountName}/apis/sql/databases/{databaseName}](https://github.com/Azure/azure-rest-api-specs/blob/7d9eaf4c9866664806a2202b02e3ab5259c86cf9/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2016-03-31/cosmos-db.json#L1482) with the operation ID `DatabaseAccounts_GetSqlDatabase`

Both paths and operation IDs are different, so Pulumi treats them as different.

@markjbrown Questions to you:

1. Are these essentially the same operation? Should we only use one in the latest version?
2. If so, why has the path changed?
3. Is there any formal way to see that these operations are the same?

**Comment by markjbrown** [comment]
The `DatabaseAccountSqlDatabase` resource is our original sql database resource when we started to create separate resource paths for our resource provider to support all of our database API's in our control plane for Cosmos DB. Prior to this we only supported DatabaseAccount and our data plane SDK created all the child resources which is still can do today.  The two resources are similar. However there are major differences in the Options parameter in that the older resource does not support autoscale.

The reason we made this change to the resource paths is because you could not use ARM resource locks on resources with paths that actually did not represent physical resources at every segment in the path. In our case, "apis" and "sql". As a result we had to modify our resource provider again to what you see today with `SqlResourceSqlDatabase` for a SQL API database.

If at all possible you should not pull these old resource definitions in from our swagger. They are functionally equivalent and people do not need to mix and match them. Also, unless you expect people to export deployments, I would not bring in anything older than the 2020-04-01 api version as there is no reason why customers would want to create new Cosmos DB resources using those old api versions. I know for us internally, we are looking to update our portal experience to only export the latest api version when exporting arm templates.

Thanks.

**Comment by markjbrown** [comment]
Mikhail. I'm checking to see if we can change our current latest stable version so that Options are not marked as required. If we cannot change it in 2020-04-01 then we will do it in our next version 2020-09-01.

Will update you on this.
