### ISSUE TITLE
Can not find a way of setting auth setting on WebApp

### ISSUE THREAD

**Issue by nicro950** [pulumi/pulumi-azure-nextgen#34]
It looks like there is no way of setting the Auth Setting on the WebApp in the new azure provider. I have only checked the C# version of it, but the only result that come close is the [`ListWebAppAuthSettings`](https://github.com/pulumi/pulumi-azure-nextgen/blob/master/sdk/dotnet/Web/V20160801/ListWebAppAuthSettings.cs). 

Is there another way of setting it, or is there something missing? Link to MS ARM template documentation for auth config https://docs.microsoft.com/en-us/azure/templates/microsoft.web/2020-06-01/sites/config-authsettings

**Comment by mikhailshilkov** [comment]
Hi @nicro950 thanks for reporting this.

Indeed, it looks like we don't expose the auth settings. The reason is the Auth Settings are not a "resource" in Pulumi's notion: it's a separate [PUT endpoint](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/web/resource-manager/Microsoft.Web/stable/2020-06-01/WebApps.json#L1098) without corresponding GET or DELETE methods.

We'll have a look at whether it's possible to extend our resource model to this kind of resources.

**Comment by nicro950** [comment]
Thank you for the explanation, we are using auth settings for a lot of our azure apis and azure functions which means we have to continue using the Pulumi.Azure provider for creating app services at least.

**Comment by mikhailshilkov** [comment]
Sure. Remember that you can use both providers side-by-side in the same program too.

**Comment by mikhailshilkov** [comment]
Another related resource with the same model is Metadata in https://github.com/Azure/azure-rest-api-specs/blob/0955eca8c1288aa8220aab34db3a66bdb6ac98cc/specification/web/resource-manager/Microsoft.Web/stable/2020-09-01/WebApps.json#L1691

**Comment by mikhailshilkov** [comment]
These resources will ship in 0.6.0
