### ISSUE TITLE
Missing Microsoft.DBforPostgreSQL/servers/configurations

### ISSUE THREAD

**Issue by XBeg9** [pulumi/pulumi-azure-nextgen#80]
https://www.pulumi.com/docs/reference/pkg/azure-nextgen/dbforpostgresql/

it's presented in non-nextGen Azure provider: https://www.pulumi.com/docs/reference/pkg/azure/postgresql/configuration/

**Comment by viveklak** [comment]
@XBeg9 This is because currently we are modeling resources which have create and delete endpoints. Configurations has a create/update endpoint but no delete. We are currently evaluating options to cover such resources. FWIW you can use the azure provider along side the azure-nextgen provider. Would creating configuration through the azure provider be an option in the meantime?

**Comment by XBeg9** [comment]
@viveklak thanks for the reply! Using azure and azure-nextgen side-by-side is what I am doing right now and it works without any issues!
